
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P0stgr3s
      POSTGRES_DB: traffic
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: traffic_backend
    environment:
      DB_URL: postgres://postgres:<password>@db:5432/traffic
    expose:
      - "3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/traffic
      dockerfile: Dockerfile
    container_name: traffic_frontend
    ports:
      - "8080:80"
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
volumes:
  pg_data:

    
